-- FixForward Iteration 1: structured, manually reviewed recall matching.
-- Run this migration on a Neon development branch before production.

BEGIN;

CREATE TABLE IF NOT EXISTS ui_appliance_categories (
    code text PRIMARY KEY,
    family_code text NOT NULL,
    family_name text NOT NULL,
    category_name text NOT NULL,
    evidence_category_id integer REFERENCES appliance_categories(id),
    active boolean NOT NULL DEFAULT true,
    notes text,
    UNIQUE (family_code, category_name)
);

INSERT INTO ui_appliance_categories
    (code, family_code, family_name, category_name, evidence_category_id, notes)
VALUES
    ('kettle', 'heating-simple-cooking', 'Heating and simple cooking', 'Kettle',
        (SELECT id FROM appliance_categories WHERE category_code = 'kettle'), NULL),
    ('toaster', 'heating-simple-cooking', 'Heating and simple cooking', 'Toaster',
        (SELECT id FROM appliance_categories WHERE category_code = 'toaster'), NULL),
    ('sandwich-press', 'heating-simple-cooking', 'Heating and simple cooking', 'Sandwich press',
        (SELECT id FROM appliance_categories WHERE category_code = 'rice_cooker_and_small_kitchen_appliances'),
        'Shares an Open Repair Alliance evidence bucket; not model-specific.'),
    ('rice-cooker', 'heating-simple-cooking', 'Heating and simple cooking', 'Rice cooker',
        (SELECT id FROM appliance_categories WHERE category_code = 'rice_cooker_and_small_kitchen_appliances'),
        'Shares an Open Repair Alliance evidence bucket; not model-specific.'),
    ('blender', 'motorised-kitchen', 'Motorised kitchen', 'Blender',
        (SELECT id FROM appliance_categories WHERE category_code = 'blender_mixer_and_food_processor'), NULL),
    ('mixer', 'motorised-kitchen', 'Motorised kitchen', 'Mixer',
        (SELECT id FROM appliance_categories WHERE category_code = 'blender_mixer_and_food_processor'), NULL),
    ('food-processor', 'motorised-kitchen', 'Motorised kitchen', 'Food processor',
        (SELECT id FROM appliance_categories WHERE category_code = 'blender_mixer_and_food_processor'), NULL),
    ('coffee-machine', 'complex-kitchen', 'Complex kitchen', 'Coffee machine',
        (SELECT id FROM appliance_categories WHERE category_code = 'coffee_machine'), NULL),
    ('air-fryer', 'complex-kitchen', 'Complex kitchen', 'Air fryer',
        (SELECT id FROM appliance_categories WHERE category_code = 'air_fryer_and_other_complex_kitchen'), NULL),
    ('microwave', 'complex-kitchen', 'Complex kitchen', 'Microwave',
        (SELECT id FROM appliance_categories WHERE category_code = 'air_fryer_and_other_complex_kitchen'),
        'Shares a broad evidence bucket; disclose this limitation.'),
    ('vacuum-cleaner', 'cleaning', 'Cleaning', 'Vacuum cleaner',
        (SELECT id FROM appliance_categories WHERE category_code = 'vacuum_cleaner'), NULL),
    ('steam-cleaner', 'cleaning', 'Cleaning', 'Steam cleaner',
        (SELECT id FROM appliance_categories WHERE category_code = 'vacuum_cleaner'),
        'No separate repair benchmark; uses the broader cleaning evidence with disclosure.'),
    ('hair-dryer', 'personal-care', 'Personal care', 'Hair dryer',
        (SELECT id FROM appliance_categories WHERE category_code = 'hair_dryer'), NULL),
    ('straightener', 'personal-care', 'Personal care', 'Straightener',
        (SELECT id FROM appliance_categories WHERE category_code = 'hair_and_beauty_appliances'), NULL),
    ('shaver', 'personal-care', 'Personal care', 'Shaver',
        (SELECT id FROM appliance_categories WHERE category_code = 'hair_and_beauty_appliances'), NULL),
    ('fan', 'air-treatment', 'Air treatment', 'Fan',
        (SELECT id FROM appliance_categories WHERE category_code = 'fan'), NULL),
    ('portable-heater', 'air-treatment', 'Air treatment', 'Portable heater',
        NULL, 'No defensible Iteration 1 repair-evidence mapping; show insufficient evidence.'),
    ('dehumidifier', 'air-treatment', 'Air treatment', 'Dehumidifier',
        (SELECT id FROM appliance_categories WHERE category_code = 'dehumidifier_and_portable_air_conditioner'), NULL),
    ('portable-air-conditioner', 'air-treatment', 'Air treatment', 'Portable air conditioner',
        (SELECT id FROM appliance_categories WHERE category_code = 'dehumidifier_and_portable_air_conditioner'), NULL)
ON CONFLICT (code) DO UPDATE SET
    family_code = EXCLUDED.family_code,
    family_name = EXCLUDED.family_name,
    category_name = EXCLUDED.category_name,
    evidence_category_id = EXCLUDED.evidence_category_id,
    notes = EXCLUDED.notes,
    active = EXCLUDED.active;

CREATE TABLE IF NOT EXISTS recall_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recall_id integer NOT NULL REFERENCES recalls(id) ON DELETE CASCADE,
    brand text,
    product_name text NOT NULL,
    manually_reviewed boolean NOT NULL DEFAULT false,
    reviewed_at date,
    review_notes text,
    UNIQUE (recall_id, brand, product_name)
);

CREATE TABLE IF NOT EXISTS recall_category_links (
    recall_product_id bigint NOT NULL REFERENCES recall_products(id) ON DELETE CASCADE,
    ui_category_code text NOT NULL REFERENCES ui_appliance_categories(code),
    PRIMARY KEY (recall_product_id, ui_category_code)
);

CREATE TABLE IF NOT EXISTS recall_identifiers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recall_product_id bigint NOT NULL REFERENCES recall_products(id) ON DELETE CASCADE,
    identifier_type text NOT NULL CHECK (
        identifier_type IN ('model', 'serial', 'barcode', 'sku', 'other')
    ),
    identifier_value text NOT NULL,
    -- Same rule as frontend normalizeIdentifier(): uppercase letters/digits only.
    normalized_value text NOT NULL CHECK (normalized_value ~ '^[A-Z0-9]+$'),
    UNIQUE (recall_product_id, identifier_type, normalized_value)
);

CREATE INDEX IF NOT EXISTS idx_recall_identifier_normalized
    ON recall_identifiers (identifier_type, normalized_value);
CREATE INDEX IF NOT EXISTS idx_recall_category_code
    ON recall_category_links (ui_category_code);

COMMIT;
