# Local build writer used by Render: validate reviewed JSON, build SQLite and regenerate src/price-snapshot.js.
# An optional argument also writes public JSON. This path uses standard-library helpers and never contacts Neon.
# The API reads the built SQLite file; the explicit static preview consumes the generated JavaScript snapshot.

"""Build the reviewed public replacement-price database using only stdlib.

Run from the project root: python data/scripts/build_price_catalogue.py
This never reads DATABASE_URL or writes to a hosted database.
"""

import argparse
import json
from pathlib import Path
import sys


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.price_catalogue import (  # noqa: E402
    CatalogueValidationError,
    DEFAULT_DATABASE_PATH,
    DEFAULT_SERVICE_FEE_PATH,
    DEFAULT_SOURCE_DIR,
    build_database,
    load_reviewed_observations,
    load_reviewed_service_fees,
    read_catalogue,
)


# Build and reread the local price database, then export the matching browser module and optional JSON payload.
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE_DIR)
    parser.add_argument("--database", type=Path, default=DEFAULT_DATABASE_PATH)
    parser.add_argument("--export-json", type=Path, help="Optional public response JSON for static preview tooling")
    parser.add_argument("--module", type=Path, default=PROJECT_ROOT / "src" / "price-snapshot.js", help="Public ESM snapshot used by the explicit static preview")
    args = parser.parse_args()
    try:
        payload = build_database(
            load_reviewed_observations(args.source_dir),
            args.database,
            load_reviewed_service_fees(args.source_dir / DEFAULT_SERVICE_FEE_PATH.name),
        )
        if read_catalogue(args.database) != payload:
            raise CatalogueValidationError("Saved public snapshot did not match the reviewed input")
        args.module.parent.mkdir(parents=True, exist_ok=True)
        args.module.write_text(
            "// Generated by data/scripts/build_price_catalogue.py from reviewed public observations.\n"
            "// Dated price examples only. This is not a live retailer feed or a Neon fallback.\n"
            + "export const PRICE_SNAPSHOT = "
            + json.dumps(payload, indent=2, ensure_ascii=False)
            + ";\n",
            encoding="utf-8",
        )
        if args.export_json:
            args.export_json.parent.mkdir(parents=True, exist_ok=True)
            args.export_json.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    except (CatalogueValidationError, OSError, RuntimeError) as error:
        print(f"Price catalogue build failed: {error}", file=sys.stderr)
        return 1
    print(f"Built and read-verified {payload['meta']['recordCount']} reviewed AUD price observations.")
    print(f"Included {payload['meta']['repairFeeRecordCount']} reviewed repair service-fee observations.")
    print(f"Observation dates: {payload['meta']['firstObservedAt']} to {payload['meta']['lastObservedAt']}")
    print(f"Public snapshot database: {args.database}")
    print(f"Public static-preview module: {args.module}")
    print("No hosted database was contacted. These are dated examples, not live prices.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
