/** Fictional challenges teach choices without diagnosing real appliances.
 * First answers count once. Retries teach the clue without inflating a score. */
import { productIcon } from './explore.js';

export const SORTING_ITEMS = Object.freeze([
  {icon:'laptop',name:'A laptop for a new learner',clue:'This fictional laptop works, has been checked by an adult and is no longer needed. A cousin would like it.',answer:'reuse',why:'A checked, working item can have another chapter with someone who wants it.'},
  {icon:'kettle',name:'A kettle with a repair quote',clue:'A qualified repairer has assessed this fictional kettle, confirmed a safe repair is possible and provided an affordable quote.',answer:'repair',why:'A professional assessment and a suitable repair can keep an item in use.'},
  {icon:'toaster',name:'A toaster at the end of its life',clue:'A qualified repairer says this fictional toaster cannot be repaired safely. An approved e-waste service accepts it.',answer:'recycle',why:'Use an appropriate collection service when a safe repair or reuse is not possible.'},
  {icon:'fan',name:'A fan for the community room',clue:'This fictional fan works, has passed an adult condition and recall check, and a community group wants it.',answer:'reuse',why:'Match a checked, useful item with someone who wants it.'},
  {icon:'blender',name:'A blender with a replaceable part',clue:'A qualified service centre has assessed this fictional blender and can safely replace the faulty part at a suitable cost.',answer:'repair',why:'A suitable professional repair can extend the useful life of an appliance.'},
  {icon:'microwave',name:'A microwave that cannot be repaired',clue:'A qualified service centre says this fictional microwave cannot be repaired safely. A collection service confirms it accepts microwaves.',answer:'recycle',why:'An appropriate e-waste collection is the next step. Do not open a real microwave.'},
  {icon:'vacuum',name:'A vacuum for another home',clue:'This fictional vacuum works well. An adult has checked its condition and recall status, and a neighbour wants it.',answer:'reuse',why:'A checked, useful item can continue to serve someone who needs it.'},
  {icon:'washing-machine',name:'A washing machine with a plan',clue:'A qualified technician has assessed this fictional washing machine and offered a safe, affordable repair with available parts.',answer:'repair',why:'An assessment, suitable parts and a reasonable quote make repair an option.'},
  {icon:'fridge',name:'A fridge for specialist collection',clue:'This fictional fridge cannot be repaired safely. A service confirms it can handle refrigerants and collect the whole item.',answer:'recycle',why:'Fridges need appropriate specialist handling. Arrange an accepted collection.'},
  {icon:'monitor',name:'A monitor for a study desk',clue:'This fictional monitor works and has been checked by an adult. A student needs it and has confirmed the connection fits.',answer:'reuse',why:'Condition, suitability and a willing recipient make this a useful reuse story.'},
]);

export const CHOICE_QUESTIONS = Object.freeze([
  {icon:'laptop',question:'Your family has an old laptop that still works. Your cousin needs one for school.',prompt:'What is the best circular choice?',options:['Give it to your cousin','Recycle it now','Keep it in a drawer','Put it in household rubbish'],details:['Wipe personal data first, then pass on the working laptop.','Take the working laptop straight to an e-waste recycler.','Leave it unused even though someone needs it.','Discard it with everyday household waste.'],answer:0,why:'A working laptop may be useful to someone else. An adult checks its condition and recalls, removes personal data and agrees the handover.'},
  {icon:'kettle',question:'A kettle has a frayed power cord.',prompt:'What should happen first?',options:['Try a different socket','Wrap the cord in tape','Stop using it and ask an adult','Give it away'],answer:2,why:'A damaged cord is a warning sign. Stop use and let an adult arrange qualified advice.'},
  {icon:'toaster',question:'A toaster has stopped working.',prompt:'What do we know?',options:['It must be recycled now','It is safe to open','Repair will be cheap','More information is needed'],answer:3,why:'A fault alone does not tell us its cause, safety or repair cost. A qualified assessment helps an adult decide.'},
  {icon:'fan',question:'A family wants its working fan to last.',prompt:'Which habit helps?',options:['Follow manufacturer care instructions','Block its vents','Ignore a damaged plug','Leave it in the rain'],answer:0,why:'Appropriate care follows the manufacturer instructions. Let an adult handle real appliances.'},
  {icon:'laptop',question:'A computer is being passed to a new owner.',prompt:'What needs attention?',options:['Only the colour','Data, condition, recalls and suitability','Only a good photo','Hide any known faults'],answer:1,why:'Responsible handover includes personal data removal, checks, honest condition information and agreement with the recipient.'},
  {icon:'blender',question:'A blender needs a repair decision.',prompt:'Which information helps?',options:['A guess about its age','An online comment alone','A qualified assessment and quote','How loudly it rattles'],answer:2,why:'A qualified assessment, quote and suitable parts help compare the specific repair and practical options.'},
  {icon:'microwave',question:'You are curious about a microwave’s parts.',prompt:'How can you explore?',options:['Open the real case','Look inside while powered','Bypass the door latch','Use a digital model'],answer:3,why:'Digital exploration keeps the real case closed. Real microwaves need qualified servicing.'},
  {icon:'fridge',question:'An adult is planning an e-waste drop-off.',prompt:'Why check service details?',options:['Accepted items and instructions vary','Every service accepts all items','Items can be left outside anytime','Item type does not matter'],answer:0,why:'Confirm the service, accepted item type, opening details and preparation instructions before making a trip.'},
  {icon:'vacuum',question:'A vacuum is listed in an official recall.',prompt:'What should its owner do?',options:['Sell it quickly','Follow the official recall instructions','Ignore it if it turns on','Give it to a friend'],answer:1,why:'A recall changes the next step even when an appliance appears to work. Follow the official notice.'},
  {icon:'monitor',question:'Your neighbourhood wants a circular approach.',prompt:'Which idea fits?',options:['Replace items every year','Hide unwanted things','Keep suitable items useful, then recover materials','Put electrical items in household rubbish'],answer:2,why:'Care, suitable repair and responsible reuse can extend use; appropriate recycling supports recovery at the end.'},
]);

/** Costs and outcomes are invented game mechanics, not environmental measurements. */
export const CITY_ROUNDS = Object.freeze([
  {title:'The school laptop shelf',copy:'Checked working laptops need a new chapter. The school has removed personal data.',options:[{label:'Match them with learners',cost:18,points:8},{label:'Run a reuse collection day',cost:12,points:6},{label:'Save the budget',cost:0,points:0}]},
  {title:'The neighbourhood repair desk',copy:'Residents need help deciding whether faulty items can be repaired safely.',options:[{label:'Fund qualified assessments',cost:22,points:9},{label:'Share reliable repair information',cost:8,points:4},{label:'Save the budget',cost:0,points:0}]},
  {title:'A collection point for e-waste',copy:'Items that cannot be safely reused or repaired need an appropriate destination.',options:[{label:'Organise an accepted collection',cost:24,points:10},{label:'Publish accepted-service details',cost:9,points:4},{label:'Save the budget',cost:0,points:0}]},
  {title:'Care for what we already have',copy:'The library wants to share manufacturer care instructions and warning signs.',options:[{label:'Host an adult-led care session',cost:17,points:7},{label:'Make a care information display',cost:7,points:3},{label:'Save the budget',cost:0,points:0}]},
  {title:'Bring the neighbourhood together',copy:'Choose the final project for your fictional circular city.',options:[{label:'Host a checked-item sharing day',cost:20,points:8},{label:'Create a local pathway guide',cost:10,points:5},{label:'Finish with the remaining budget',cost:0,points:0}]},
]);

const MODES=[{id:'fix-it',title:'Fix-it Station',tag:'BEGINNER MODE',icon:'kettle',copy:'Read the clues, then drag 3D appliances and everyday rubbish to a workshop station or the right kerbside bin.',label:'Play',colour:'yellow'},{id:'choices',title:'Circular Choices',tag:'INTERMEDIATE MODE',icon:'laptop',copy:'Read a real-life scenario and choose the best answer from four options.',label:'Play',colour:'blue'},{id:'city',title:'Circular City',tag:'ADVANCED MODE',icon:'fridge',copy:'Manage a city with too much e-waste. Improve the system and reduce landfill.',label:'Play',colour:'mint'}];
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

export function mountLearning(host,{route='learn',onNavigate=()=>{},onLearn=()=>{},onAward=()=>{},signal}={}) {
  if(signal?.aborted)return ()=>{};
  const controller=new host.ownerDocument.defaultView.AbortController();
  const game=new URLSearchParams(String(route).split('?')[1]||'').get('game');
  const mode=MODES.find(item=>item.id===game);
  let index=0,score=0,streak=0,attempted=false,resolved=false,finished=false,budget=100,feedback=null;
  const projects=[],awarded=new Set();
  const cleanup=()=>{controller.abort();signal?.removeEventListener('abort',cleanup);};
  signal?.addEventListener('abort',cleanup,{once:true});
  function award(id,title,detail,points=10){if(awarded.has(id))return;awarded.add(id);onLearn({id,title,detail});onAward(id,points,host.querySelector('.challenge-feedback')||host);}
  // Stories include three items outside the explorable catalogue, so draw those
  // explicitly instead of allowing the catalogue's generic kettle fallback.
  function art(icon){const extra={'washing-machine':'<rect x="12" y="6" width="40" height="52" rx="4"/><path d="M12 17h40M18 12h10"/><circle cx="32" cy="37" r="14"/><circle cx="44" cy="12" r="1"/>',fridge:'<rect x="17" y="5" width="31" height="54" rx="4"/><path d="M17 24h31M23 13v5m0 14v9"/>',monitor:'<rect x="6" y="8" width="52" height="36" rx="3"/><path d="M28 44v10m8-10v10M20 56h24M6 38h52"/>'};const svg=extra[icon]?`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">${extra[icon]}</svg>`:productIcon(icon);return `<div class="challenge-art" aria-hidden="true">${svg}</div>`;}
  function modeArt(id){const bins='<rect x="52" y="44" width="176" height="81" rx="9" fill="#dcecf7"/><rect x="65" y="55" width="150" height="54" rx="4" fill="#fff"/><path d="M39 132h202l-14 11H54z" fill="#466584"/>'+[['Repair',25,'#d9efd8'],['Reuse',104,'#dceffa'],['Recycle',183,'#e7e0f5']].map(([label,x,fill])=>`<rect x="${x}" y="164" width="70" height="58" rx="8" fill="${fill}"/><text x="${x+35}" y="199" text-anchor="middle" fill="#344b62" font-size="13">${label}</text>`).join('');const answers='<rect x="25" y="28" width="230" height="50" rx="8" fill="#e4f2fb"/><path d="M47 48h132M47 60h185" stroke="#7da2bc" stroke-width="5" stroke-linecap="round"/>'+[0,1,2,3].map(n=>`<rect x="${25+n%2*120}" y="${96+Math.floor(n/2)*65}" width="110" height="53" rx="8" fill="${['#e3f4eb','#e7f1fc','#fff0dd','#f0e9fc'][n]}"/><circle cx="${44+n%2*120}" cy="${116+Math.floor(n/2)*65}" r="9" fill="#ffffff"/><text x="${44+n%2*120}" y="${120+Math.floor(n/2)*65}" text-anchor="middle" font-size="11" fill="#46617b">${'ABCD'[n]}</text><path d="M${61+n%2*120} ${114+Math.floor(n/2)*65}h57" stroke="#8da1b1" stroke-width="4" stroke-linecap="round"/>`).join('');const city='<path d="M15 219h250" stroke="#b6d8b0" stroke-width="16" stroke-linecap="round"/><rect x="28" y="94" width="62" height="117" rx="5" fill="#b0cfeb"/><rect x="101" y="57" width="77" height="154" rx="5" fill="#aacbb7"/><rect x="190" y="117" width="60" height="94" rx="5" fill="#edc59d"/>'+[0,1,2].map(n=>`<path d="M42 ${115+n*29}h14m15 0h5M117 ${81+n*35}h18m13 0h14M204 ${136+n*23}h11m13 0h8" stroke="#fff" stroke-width="9"/>`).join('');return `<svg viewBox="0 0 280 245" aria-hidden="true">${id==='fix-it'?bins:id==='choices'?answers:city}</svg>`;}
  function heading(title,copy){return `<div class="challenge-top"><a href="#learn" data-hub>← All challenges</a><span>LEARN BY DOING</span></div><header class="challenge-heading"><h1>${title}</h1><p>${copy}</p></header>`;}
  function renderHub(){host.innerHTML=`<section class="challenge-page"><header class="challenge-hub-heading"><h1>Choose your challenge</h1><p>Learn how circular choices work by playing through three different game modes.</p></header><div class="challenge-grid">${MODES.map(item=>`<article class="challenge-card ${item.colour}"><div class="challenge-card-art">${modeArt(item.id)}</div><div class="challenge-card-content"><p class="challenge-eyebrow">${item.tag}</p><h2>${item.title}</h2><p>${item.copy}</p><a class="challenge-button" href="#learn?game=${item.id}" data-game="${item.id}">${item.label}<span aria-hidden="true">→</span></a></div></article>`).join('')}</div><a class="scrapworks-feature" href="#scrapworks"><span class="scrapworks-feature-badge">NEW · STRATEGY GAME · AGES 10–13</span><strong>Scrapworks</strong><span>Run the town’s e-waste recovery hub. Inspect devices, spend limited repair tokens and restore a neglected town over 8 shifts.</span><span class="challenge-button">Open Scrapworks <span aria-hidden="true">→</span></span></a><div class="challenge-goal"><span class="goal-mark" aria-hidden="true">✦</span><p><strong>A little practice goes a long way.</strong> Aim for 8 out of 10 first answers in Fix-it Station and Circular Choices. Every challenge is ready to play.</p></div><p class="challenge-note">These are fictional learning stories. Explore digital objects and let an adult handle real appliances.</p></section>`;}
  function feedbackMarkup(){return feedback?`<div class="challenge-feedback ${feedback.correct?'is-correct':'is-retry'}" role="status"><strong>${feedback.title}</strong><p>${feedback.copy}</p></div>`:'<div class="challenge-feedback" role="status" hidden></div>';}
  function renderQuiz(focus=false){const item=(game==='fix-it'?SORTING_ITEMS:CHOICE_QUESTIONS)[index],options=game==='fix-it'?['repair','reuse','recycle']:item.options;host.innerHTML=`<section class="challenge-page challenge-game">${heading(mode.title,game==='fix-it'?'Follow the clue. Choose a next chapter.':'Intermediate Mode')}<div class="challenge-progress"><span>${game==='fix-it'?'Item':'Question'} ${index+1} / 10</span><span>Streak ${streak}</span><span>Sparks ${score*5}</span><progress max="10" value="${index}" aria-label="Completed questions"></progress></div><article class="challenge-play-card ${game==='choices'?'blue':mode.colour}">${game==='fix-it'?art(item.icon):''}<div class="challenge-scenario"><div class="challenge-question"><p class="challenge-eyebrow">${game==='fix-it'?'A FICTIONAL ITEM':'WHAT WOULD YOU CHOOSE?'}</p><h2 tabindex="-1">${escape(item.name||item.question)}</h2>${item.clue?`<p class="challenge-clue">${escape(item.clue)}</p>`:`<p class="challenge-clue">${item.prompt}</p>`}</div><div class="challenge-options ${game==='fix-it'?'sorting-options':''}">${options.map((option,n)=>`<button type="button" data-answer="${game==='fix-it'?option:n}" ${resolved?'disabled':''}><span class="answer-letter" aria-hidden="true">${game==='fix-it'?['↺','⇄','♻'][n]:'ABCD'[n]}</span><strong>${escape(game==='fix-it'?option[0].toUpperCase()+option.slice(1):option)}</strong>${item.details?`<span class="answer-detail">${escape(item.details[n])}</span>`:''}${game==='choices'?'<span class="answer-choose">Choose →</span>':''}</button>`).join('')}</div>${feedbackMarkup()}${resolved?`<button class="challenge-button" type="button" data-next>${index===9?'See my results':'Next '+(game==='fix-it'?'item':'question')} →</button>`:''}</div></article><p class="challenge-note">Goal: 8 out of 10 first answers. Retries teach the clue; sparks count first answers only. Real items need their own checks.</p></section>`;if(focus)host.querySelector('h2').focus();}
  function renderResults(){host.innerHTML=`<section class="challenge-page challenge-results">${heading(mode.title,'Keep the ideas. Try another challenge.')}<div class="challenge-result-mark" aria-hidden="true">✦</div><h2 tabindex="-1">${game==='city'?'Your city has a new chapter.':'A little wiser. A little more circular.'}</h2>${game==='city'?`<p class="challenge-result-score">${score}<span> city points</span></p><p>You finished five rounds with <strong>${budget} of 100 tokens</strong> remaining.</p><ul class="city-projects">${projects.map(item=>`<li>${escape(item)}</li>`).join('')}</ul><p>These points and tokens are fictional game values, not measured environmental savings.</p>`:`<p class="challenge-result-score">${score}<span> / 10 first answers</span></p><p>${score>=8?'You reached the 8 out of 10 practice goal.':'You completed every story. The practice goal is 8 out of 10 first answers; try again whenever you like.'}</p><p>Retries help you learn. They do not change your first-answer score.</p>`}<div class="challenge-result-actions"><button type="button" class="challenge-button" data-restart>Play again ↻</button><a class="challenge-button secondary" href="#learn" data-hub>Choose another challenge →</a></div></section>`;host.querySelector('h2').focus();}
  function renderCity(focus=false){const round=CITY_ROUNDS[index];host.innerHTML=`<section class="challenge-page challenge-game">${heading(mode.title,'Build a fictional neighbourhood, one thoughtful choice at a time.')}<div class="city-scoreboard"><span><strong>Round ${index+1}</strong> of 5</span><span><strong>${budget}</strong> tokens left</span><span><strong>${score}</strong> city points</span></div><div class="city-illustration" aria-hidden="true"><span class="city-building building-one"></span><span class="city-tree"></span><span class="city-building building-two"></span><span class="city-building building-three"></span><span class="city-tree"></span><span class="city-building building-four"></span></div><article class="city-round"><p class="challenge-eyebrow">YOUR NEXT CITY DECISION</p><h2 tabindex="-1">${round.title}</h2><p>${round.copy}</p><div class="city-options">${round.options.map((option,n)=>`<button type="button" data-city="${n}" ${resolved||option.cost>budget?'disabled':''}><strong>${option.label}</strong><span>${option.cost} tokens · ${option.points} city points</span>${option.cost>budget?'<small>More tokens needed</small>':''}</button>`).join('')}</div>${feedbackMarkup()}${resolved?`<button class="challenge-button" type="button" data-next>${index===4?'See my city':'Next round'} →</button>`:''}</article><p class="challenge-note">100 imaginary tokens. Five fictional decisions. Costs and city points are game values, not real prices or environmental measurements.</p></section>`;if(focus)host.querySelector('h2').focus();}
  function next(){if(!resolved||finished)return;const limit=game==='city'?5:10;if(index===limit-1){finished=true;award(`challenge:${game}:complete`,`${mode.title} completed`,game==='city'?`Finished five fictional rounds with ${score} city points.`:`${score} of 10 first answers correct.`);renderResults();return;}index++;attempted=false;resolved=false;feedback=null;game==='city'?renderCity(true):renderQuiz(true);}
  function handleClick(event){const target=event.target.closest('button,a');if(!target||!host.contains(target))return;if(target.matches('[data-game]')){event.preventDefault();onNavigate(`learn?game=${target.dataset.game}`);return;}if(target.matches('[data-hub]')){event.preventDefault();onNavigate('learn');return;}if(target.matches('[data-restart]')){index=0;score=0;streak=0;budget=100;attempted=false;resolved=false;finished=false;feedback=null;projects.length=0;game==='city'?renderCity(true):renderQuiz(true);return;}if(target.matches('[data-next]')){next();return;}if(finished||resolved||target.disabled)return;
    if(target.matches('[data-answer]')){const item=(game==='fix-it'?SORTING_ITEMS:CHOICE_QUESTIONS)[index],correct=String(item.answer)===target.dataset.answer;const firstCorrect=!attempted&&correct;if(firstCorrect){score++;streak++;}else if(!correct)streak=0;attempted=true;resolved=correct;feedback=correct?{correct:true,title:'Good thinking!',copy:item.why}:{correct:false,title:'Take another look at the clue.',copy:'You can try again. Think about what is known, whether the item is useful and who needs to check it.'};if(correct)award(`challenge:${game}:${index}`,item.name||item.question,item.why,firstCorrect?5:0);const chosen=target.dataset.answer;renderQuiz();host.querySelector(correct?'[data-next]':`[data-answer="${chosen}"]`).focus();return;}
    if(target.matches('[data-city]')&&game==='city'){const option=CITY_ROUNDS[index].options[Number(target.dataset.city)];if(!option||option.cost>budget)return;budget-=option.cost;score+=option.points;projects.push(option.label);resolved=true;feedback={correct:true,title:option.cost?'Your city takes a step forward.':'Budget saved.',copy:option.cost?`${option.label} adds ${option.points} fictional city points. You have ${budget} tokens left.`:`You keep ${budget} tokens for the decisions ahead.`};award(`challenge:city:${index}`,CITY_ROUNDS[index].title,option.label,option.points);renderCity();host.querySelector('[data-next]').focus();}
  }
  host.addEventListener('click',handleClick,{signal:controller.signal});
  if(!mode)renderHub();else if(game==='city')renderCity();else renderQuiz();
  return cleanup;
}
