// On-device browser narration. Voices, pitch and pause behaviour vary by platform.
export class Storyteller{
 constructor({caption=()=>{},status=()=>{}}={}){this.caption=caption;this.status=status;this.token=0;this.timer=0;this.active=false;this.paused=false;this.speaking=false;this.index=0;this.lines=[];this.rate=.91;this.voiceName='';this.current=null;this.available=typeof window!=='undefined'&&'speechSynthesis'in window;}
 voices(){if(!this.available)return [];return window.speechSynthesis.getVoices().filter(v=>/^en\b/i.test(v.lang));}
 chosenVoice(){const voices=this.voices();return voices.find(v=>v.name===this.voiceName)||voices.find(v=>v.lang==='en-AU'&&/Karen|Catherine|Natural|Enhanced/i.test(v.name))||voices.find(v=>/Samantha|Karen|Natural|Enhanced/i.test(v.name))||voices.find(v=>v.lang==='en-AU')||voices[0];}
 play(lines){this.stop();if(!this.available){this.caption('Your browser cannot read aloud. The story words are still here.');this.status('unavailable');return false;}this.lines=lines.map(l=>typeof l==='string'?{text:l,kind:'story'}:l).filter(l=>l.text);this.index=0;this.active=true;this.paused=false;this.status('playing');this.next(this.token);return true;}
 next(token){if(token!==this.token||!this.active||this.paused)return;if(this.index>=this.lines.length){this.active=false;this.speaking=false;this.status('finished');return;}const line=this.lines[this.index],u=new SpeechSynthesisUtterance(line.text);u.lang='en-AU';const voice=this.chosenVoice();if(voice)u.voice=voice;u.rate=Math.max(.7,Math.min(1.1,this.rate+(line.kind==='celebrate'?.03:line.kind==='clue'?-.04:0)));u.pitch=line.kind==='question'?1.13:line.kind==='celebrate'?1.17:line.kind==='clue'?.98:1.04;u.volume=1;this.current=u;this.speaking=true;this.caption(line.text,this.index,this.lines.length);u.onend=()=>{if(token!==this.token)return;this.current=null;this.speaking=false;this.index++;if(!this.paused)this.timer=setTimeout(()=>this.next(token),line.pause??(line.kind==='question'?800:500));};u.onerror=e=>{if(token!==this.token||['canceled','interrupted'].includes(e.error))return;this.active=false;this.speaking=false;this.status('error');this.caption('The voice could not start. Try Listen again, or read the story words.');};window.speechSynthesis.speak(u);return true;}
 pause(){if(!this.active||this.paused)return;this.paused=true;clearTimeout(this.timer);if(this.speaking)window.speechSynthesis.pause();this.status('paused');}
 resume(){if(!this.active||!this.paused)return;this.paused=false;this.status('playing');if(this.speaking)window.speechSynthesis.resume();else this.next(this.token);}
 stop(){this.token++;clearTimeout(this.timer);if(this.available)window.speechSynthesis.cancel();this.active=false;this.paused=false;this.speaking=false;this.current=null;this.status('stopped');}
}
export function softChime(kind='clue'){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;softChime.context??=new C();const c=softChime.context;if(c.state==='suspended')c.resume();const t=c.currentTime,notes=kind==='success'?[523.25,659.25,783.99]:[587.33,783.99];notes.forEach((freq,i)=>{const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=freq;o.connect(g);g.connect(c.destination);g.gain.setValueAtTime(0,t+i*.09);g.gain.linearRampToValueAtTime(.045,t+i*.09+.015);g.gain.exponentialRampToValueAtTime(.001,t+i*.09+.21);o.start(t+i*.09);o.stop(t+i*.09+.23);});}catch{}}
