// Screen-sized activity layouts; no user-agent sniffing or hardware-test claims.
const sheet=document.createElement('link');sheet.rel='stylesheet';sheet.href=new URL('./tablet.css',import.meta.url).href;document.head.append(sheet);
const kind=location.pathname.includes('/home/')?'home':location.pathname.includes('/lab/')?'lab':'discovery';document.body.classList.add(kind+'-tablet');
const typeSize=()=>document.body.classList.toggle('large-type',parseFloat(window.getComputedStyle(document.documentElement).fontSize)>22);typeSize();new MutationObserver(typeSize).observe(document.documentElement,{attributes:true,attributeFilter:['style','class']});
const size=()=>{document.documentElement.style.setProperty('--play-height',(window.visualViewport?.height||window.innerHeight)+'px');};size();window.addEventListener('resize',size);window.visualViewport?.addEventListener('resize',size);
const host=document.querySelector(kind==='home'?'.home-header nav':kind==='lab'?'.site-header':'.reading');
if(host&&document.fullscreenEnabled){const b=document.createElement('button');b.className='screen-toggle';b.textContent='Full screen';b.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{b.textContent='Use browser full screen';}};document.addEventListener('fullscreenchange',()=>b.textContent=document.fullscreenElement?'Exit full screen':'Full screen');host.append(b);}
// Optional detail opens over the activity. Move, rather than clone, its inputs so
// existing energy handlers, labels and IDs remain the source of truth.
let readingDialogId=0;
document.addEventListener('click',event=>{const summary=event.target.closest('summary');if(!summary||!summary.parentElement.matches('.detail,.word-help,.share-discovery,.extra-fact,.energy-settings,.lab-sources,.clue-review'))return;
 event.preventDefault();const parent=summary.parentElement,nodes=[...parent.childNodes].filter(n=>n!==summary),dialog=document.createElement('dialog');dialog.className='reading-dialog';const heading=document.createElement('h2');heading.id='reading-dialog-title-'+(++readingDialogId);heading.textContent=summary.textContent.replace(/\+$/,'').trim();dialog.setAttribute('aria-labelledby',heading.id);const close=document.createElement('button');close.textContent='Back to activity';close.className='primary';close.onclick=()=>dialog.close();const content=document.createElement('div');content.className='reading-content';content.append(...nodes);dialog.append(heading,content,close);document.body.append(dialog);dialog.addEventListener('close',()=>{parent.append(...nodes);dialog.remove();summary.focus({preventScroll:true});},{once:true});dialog.showModal();
});
if(kind==='home'){
 const choices=document.querySelector('#avatar-choices'),wrap=document.createElement('div'),nav=document.createElement('div');wrap.className='avatar-controls';nav.className='avatar-categories';nav.setAttribute('role','group');nav.setAttribute('aria-label','Choose what to customise');choices.before(wrap);wrap.append(nav,choices);let category=0;
 const labels=['Skin','Hair colour','Hair style','Expression','Outfit','Glasses'];
 const show=()=>{[...choices.querySelectorAll('fieldset'),choices.querySelector('.glasses-toggle')].filter(Boolean).forEach((el,i)=>el.hidden=i!==category);nav.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===category)));};
 labels.forEach((label,i)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{category=i;show();};nav.append(b);});new MutationObserver(show).observe(choices,{childList:true});show();
}
if(kind==='lab'){
 const panel=document.querySelector('#panel-parts'),topics=[['purpose','What it does','.lesson:not(.care-tip)'],['impact','Our planet','.planet-note'],['care','Care tip','.care-tip']],nav=document.createElement('div');nav.className='part-topic-nav';nav.setAttribute('role','group');nav.setAttribute('aria-label','Choose a part lesson');
 for(const[id,label]of topics){const b=document.createElement('button');b.textContent=label;b.dataset.lessonTopic=id;b.onclick=()=>choose(id);nav.append(b);}
 function choose(id){panel.dataset.topic=id;for(const[key,,selector]of topics)panel.querySelector(selector).hidden=key!==id;nav.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lessonTopic===id)));}
 document.querySelector('#part-material').after(nav);choose('purpose');
 const energy=document.querySelector('#panel-energy');if(energy.querySelector('#annual-saving')){const settings=document.createElement('details');settings.className='energy-settings';const summary=document.createElement('summary');summary.textContent='Daily use, grid & calculation';settings.append(summary,energy.querySelector('#annual-saving'),energy.querySelector('.field-row'),energy.querySelector('#factor-label'),energy.querySelector('.detail'));energy.querySelector('.boundary-note').before(settings);}
 const care=document.querySelector('#panel-care'),steps=[...care.querySelectorAll('.life-list>li')],controls=document.createElement('div');controls.className='care-pages';const back=document.createElement('button'),next=document.createElement('button'),count=document.createElement('span');let i=0;back.textContent='Previous tip';next.textContent='Next tip';back.onclick=()=>show(i-1);next.onclick=()=>show(i+1);controls.append(back,count,next);care.querySelector('.life-list').after(controls);function show(n){i=Math.max(0,Math.min(steps.length-1,n));steps.forEach((e,index)=>e.hidden=index!==i);back.disabled=i===0;next.disabled=i===steps.length-1;count.textContent=`Tip ${i+1} of ${steps.length}`;}show(0);
 const design=document.createElement('details');design.className='detail';const designTitle=document.createElement('summary');designTitle.textContent='What makes care easier?';design.append(designTitle,care.querySelector('.planet-note'));care.append(design);
 const sources=document.querySelector('.lab-footer details');sources.classList.add('lab-sources');const sourceButton=document.createElement('button');sourceButton.className='lab-source-button';sourceButton.textContent='Model & sources';sourceButton.onclick=()=>sources.querySelector('summary').click();document.querySelector('.stage').append(sourceButton);
}
