// Native Pointer Events keep the same drag flow for a finger, pen or mouse.
export function installTouchSorting(root,{onDrop,onPickup=()=>{}}){let drag=null,ghost=null,active=null,raf=0;
 function clear(){cancelAnimationFrame(raf);if(drag?.handle?.hasPointerCapture?.(drag.pointer))drag.handle.releasePointerCapture(drag.pointer);drag=null;ghost?.remove();ghost=null;active?.classList.remove('touch-over');active=null;document.body.classList.remove('sorting-drag');}
 root.addEventListener('pointerdown',e=>{const h=e.target.closest('[data-grab]');if(!h||h.disabled||e.isPrimary===false)return;e.preventDefault();clear();h.setPointerCapture?.(e.pointerId);drag={pointer:e.pointerId,handle:h,id:h.dataset.grab,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};onPickup();ghost=document.createElement('div');ghost.className='touch-ghost';ghost.setAttribute('aria-hidden','true');const picture=root.querySelector('ff-object')?.snapshot?.();if(picture){const image=new Image();image.src=picture;ghost.append(image);}else ghost.textContent=root.querySelector('.object-icon,.model-fallback-icon')?.textContent||'✦';document.body.append(ghost);place(e.clientX,e.clientY);document.body.classList.add('sorting-drag');});
 function place(x,y){if(ghost)ghost.style.transform=`translate3d(${x-62}px,${y-90}px,0) rotate(-5deg)`;}
 function scroll(){if(!drag)return;if(drag.y>innerHeight-75)window.scrollBy(0,6);else if(drag.y<85)window.scrollBy(0,-6);raf=requestAnimationFrame(scroll);}
 root.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer)return;e.preventDefault();const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(Math.hypot(dx,dy)>6)drag.moved=true;drag.x=e.clientX;drag.y=e.clientY;place(e.clientX,e.clientY);const under=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-answer]');const target=under&&!under.disabled&&root.contains(under)?under:null;if(target!==active){active?.classList.remove('touch-over');active=target;active?.classList.add('touch-over');}if(!raf)scroll();});
 root.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointer)return;const answer=active?.dataset.answer,item=drag.id,moved=drag.moved;clear();if(answer)onDrop(answer,item);else if(!moved){root.querySelector('.sort-targets')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}});
 root.addEventListener('pointercancel',clear);window.addEventListener('pagehide',clear);return clear;
}
export function celebrate(root){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const target=root.querySelector('.answer.correct,.earned-stamp,.finish-emblem');if(!target)return;target.classList.remove('little-celebration');void target.offsetWidth;target.classList.add('little-celebration');setTimeout(()=>target.classList.remove('little-celebration'),750);}
export function clueRipple(root,index){const clue=root.querySelector(`[data-clue="${index}"]`);clue?.classList.add('clue-reveal');root.querySelector('ff-object')?.react?.();setTimeout(()=>clue?.classList.remove('clue-reveal'),900);}
